# Generated by Django 4.0 on 2022-04-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspi', '0007_ledstat_imp_1_ledstat_imp_2_ledstat_imp_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledstat',
            name='led4_status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='ledstat',
            name='led5_status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='ledstat',
            name='led6_status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='ledstat',
            name='led7_status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
